packages:
  - packages/**
  - demo

allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: false
  prisma: false

catalog:
  '@better-auth/prisma-adapter': 1.6.23
  '@types/node': ^25.6.2
  auth: 1.6.23
  better-auth: 1.6.23
  bumpp: ^11.1.0
  tsdown: ^0.22.0
  typescript: ^6.0.3
  vitest: ^4.1.7
  zod: ^4.4.3
